package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/andragon31/Ragnarok/internal/fenrir/config"
	"github.com/andragon31/Ragnarok/internal/fenrir/database"
	"github.com/andragon31/Ragnarok/internal/fenrir/mcp"
	"github.com/andragon31/Ragnarok/internal/fenrir/memory"
	"github.com/andragon31/Ragnarok/internal/fenrir/scanner"
	"github.com/andragon31/Ragnarok/internal/version"
)

var Version = version.Version

func RunServe(port int, configPath, dataDir string) error {
	if dataDir == "" {
		home, _ := os.UserHomeDir()
		dataDir = filepath.Join(home, ".fenrir")
	}

	cfg := &config.Config{
		Port:    port,
		DataDir: dataDir,
	}

	if configPath != "" {
		var err error
		cfg, err = config.LoadConfig(configPath)
		if err != nil {
			return fmt.Errorf("failed to load config: %w", err)
		}
	}

	dbPath := filepath.Join(cfg.DataDir, "fenrir.db")
	db, err := database.NewDB(dbPath)
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	if err := database.InitSchema(db); err != nil {
		return fmt.Errorf("failed to init schema: %w", err)
	}

	ctx := context.Background()
	server := mcp.NewServer(cfg, db)

	log.Printf("Starting Fenrir server on port %d...", port)
	return server.Run(ctx)
}

func RunInit(projectName, dataDir string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get current directory: %w", err)
	}

	agentsPath := filepath.Join(cwd, "AGENTS.md")
	if _, err := os.Stat(agentsPath); os.IsNotExist(err) {
		if err := GenerateAgentsMD(projectName); err != nil {
			fmt.Printf("  Warning: Could not generate AGENTS.md: %v\n", err)
		} else {
			fmt.Printf("  Generated: %s\n", agentsPath)
		}
	} else {
		fmt.Printf("  AGENTS.md already exists: %s\n", agentsPath)
	}

	if dataDir == "" {
		home, _ := os.UserHomeDir()
		dataDir = filepath.Join(home, ".fenrir")
	}

	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return fmt.Errorf("failed to create data dir: %w", err)
	}

	dbPath := filepath.Join(dataDir, "fenrir.db")
	db, err := database.NewDB(dbPath)
	if err != nil {
		fmt.Printf("  Warning: Database initialization failed: %v\n", err)
		return nil
	}
	defer db.Close()

	if err := database.InitSchema(db); err != nil {
		return fmt.Errorf("failed to init schema: %w", err)
	}

	cfg := &config.Config{
		Project: projectName,
		Version: Version,
		Port:    7437,
		DataDir: dataDir,
	}

	configPath := filepath.Join(dataDir, "config.json")
	if err := cfg.Save(configPath); err != nil {
		return fmt.Errorf("failed to save config: %w", err)
	}

	fmt.Printf("✓ Initialized Fenrir for project: %s\n", projectName)
	return nil
}

func GenerateAgentsMD(projectName string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}

	analyzer := scanner.NewProjectAnalyzer(cwd)
	analysis, err := analyzer.Analyze()
	if err != nil {
		return err
	}

	var buf strings.Builder
	buf.WriteString("# " + projectName + " - Agent Guidelines\n\n")
	buf.WriteString("> Auto-generated by Fenrir v" + Version + " on project scan\n\n")
	buf.WriteString("## Project Stack\n\n")
	if analysis.Stack.Language != "" {
		buf.WriteString("- **Language**: " + analysis.Stack.Language + "\n")
	}
	buf.WriteString("- **Architecture**: " + analysis.Architecture.Type + "\n\n")

	// ... (Rest of simplified logic for brevity, can be expanded later if needed)
	buf.WriteString("## Modules\n\n")
	for _, m := range analysis.Modules {
		buf.WriteString("- `" + m.Path + "` (" + m.Type + ")\n")
	}

	agentsPath := filepath.Join(cwd, "AGENTS.md")
	return os.WriteFile(agentsPath, []byte(buf.String()), 0644)
}

func RunScan(projectPath, layer string) {
	absPath, err := filepath.Abs(projectPath)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	analyzer := scanner.NewProjectAnalyzer(absPath)
	analysis, err := analyzer.Analyze()
	if err != nil {
		fmt.Printf("Error analyzing project: %v\n", err)
		return
	}

	fmt.Printf("Project: %s\n", filepath.Base(analysis.Path))
	fmt.Printf("Language: %s\n", analysis.Stack.Language)
	fmt.Printf("Architecture: %s\n", analysis.Architecture.Type)
}

func RunBootstrap(projectPath string) {
	absPath, _ := filepath.Abs(projectPath)
	analyzer := scanner.NewProjectAnalyzer(absPath)
	analysis, _ := analyzer.Analyze()
	analysis.Name = filepath.Base(absPath)

	bootstrapDir := filepath.Join(absPath, ".ragnarok")
	os.MkdirAll(bootstrapDir, 0755)

	skillsConfig := scanner.GenerateSkillsConfig(analysis)
	skillsFile := filepath.Join(bootstrapDir, "skills.json")
	skillsJSON, _ := json.MarshalIndent(skillsConfig, "", "  ")
	os.WriteFile(skillsFile, skillsJSON, 0644)
	fmt.Printf("✓ Created: %s\n", skillsFile)

	rulesConfig := scanner.GenerateRulesConfig(analysis)
	rulesFile := filepath.Join(bootstrapDir, "rules.json")
	rulesJSON, _ := json.MarshalIndent(rulesConfig, "", "  ")
	os.WriteFile(rulesFile, rulesJSON, 0644)
	fmt.Printf("✓ Created: %s\n", rulesFile)

	standardsConfig := scanner.GenerateStandardsConfig(analysis)
	standardsFile := filepath.Join(bootstrapDir, "standards.json")
	standardsJSON, _ := json.MarshalIndent(standardsConfig, "", "  ")
	os.WriteFile(standardsFile, standardsJSON, 0644)
	fmt.Printf("✓ Created: %s\n", standardsFile)
}

func RunStats(configPath string) error {
	home, _ := os.UserHomeDir()
	if configPath == "" {
		configPath = filepath.Join(home, ".fenrir", "config.json")
	}

	cfg, err := config.LoadConfig(configPath)
	if err != nil {
		return err
	}

	dbPath := filepath.Join(cfg.DataDir, "fenrir.db")
	db, err := database.NewDB(dbPath)
	if err != nil {
		return err
	}
	defer db.Close()

	store := memory.NewMemoryStore(db)
	stats, err := store.GetStats()
	if err != nil {
		return err
	}

	fmt.Printf("Observations: %d\n", stats.TotalObservations)
	fmt.Printf("Specs: %d\n", stats.TotalSpecs)
	return nil
}
