# .goreleaser.yaml
version: 2

project_name: ragnarok

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: fenrir
    main: ./cmd/fenrir/main.go
    binary: fenrir
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: hati
    main: ./cmd/hati/main.go
    binary: hati
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: skoll
    main: ./cmd/skoll/main.go
    binary: skoll
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: tyr
    main: ./cmd/tyr/main.go
    binary: tyr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: rag
    main: ./cmd/rag/main.go
    binary: rag
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
