package unified

import (
	"fmt"
)

func getToolDescription(name string) string {
	descriptions := map[string]string{
		// Fenrir (Memory)
		"mem_save":            "Save a persistent development observation to Fenrir memory, including context, rationale, and lessons learned.",
		"mem_find":            "Perform a semantic and full-text search (FTS5) over the stored memory observations to retrieve relevant past context.",
		"mem_context":         "Retrieve the recent history and contextual observations associated with a specific module or file path.",
		"mem_timeline":        "Get a chronological list of recent development events and observations to understand project evolution.",
		"mem_stats":           "Retrieve high-level statistics from the Fenrir memory layer, such as total observation counts and database health.",
		"mem_session_start":   "Initiate a new development session with a specific goal, allowing for grouping of related observations and context.",
		"mem_session_end":     "Conclude the current development session and generate a summarized distillation of the achievements and findings.",
		"mem_get_observation": "Retrieve the full details of a specific memory observation by its unique identifier for deep inspection.",
		"mem_project_summary": "Retrieve a comprehensive summary of project activity, key milestones reached, and overall memory health from Fenrir.",
		"mem_save_prompt":     "Log a raw interaction prompt and its corresponding response to the memory layer for future pattern analysis.",
		"spec_save":           "Persist a formal architectural specification, technical constraint, or project rule in the governance layer.",
		"spec_list":           "List all registered specifications and governance rules, optionally filtered by module or category.",
		"spec_delta":          "Analyze the differences between a plan and a specification to identify potential architectural drifting or violations.",
		"spec_impact":         "Analyze how a proposed change or new requirement impacts the existing specifications and architectural constraints.",
		"spec_check":          "Perform a compliance check on a specific module or code snippet to ensure it adheres to the registered specifications.",
		"project_scan":        "Execute a comprehensive project scan to detect the technology stack, architecture patterns, and directory structure.",
		"project_bootstrap":   "Initialize a new Ragnarok project structure, creating essential metadata and preparing module-level environments.",
		"skill_generate":      "Automatically generate default skill structures based on the detected project stack to accelerate agent onboarding.",
		"rules_generate":      "Automatically derivation of orchestration rules and quality standards based on the current project's architecture.",
		"standards_generate":  "Generate project-specific quality standards (lint/test/format) matching the detected tech stack requirements.",
		"prompt_analyze":      "Analyze the current prompt context to extract implicit requirements, risks, and recommended tool sequences.",
		"agents_md_get":       "Retrieve the content of the AGENTS.md document to understand current agent guidelines and project architecture.",

		// Hati (Planning)
		"plan_create":          "Initialize a new development plan root with a title and high-level description of the primary objective.",
		"plan_list":            "List all development plans stored in Hati, providing their status, risk level, and progress metrics.",
		"plan_get":             "Retrieve the complete structure of a specific development plan, including all associated phases and tasks.",
		"plan_complete":        "Mark a development plan as successfully finished, archiving its context and providing a final results summary.",
		"plan_abandon":         "Formally abandon a development plan, providing a reason for the record and releasing all associated resources.",
		"plan_resume":          "Reactivate a previously abandoned or paused development plan to continue progress from the last known state.",
		"plan_revise":          "Submit a request to re-plan or update an existing plan, allowing for structural modifications based on new requirements.",
		"plan_blockers":        "Identify all active blockers and cross-plan dependencies currently impeding the progress of the target plan.",
		"plan_dependencies":    "List or add inter-project and inter-plan dependencies, ensuring proper sequencing in the orchestration layer.",
		"plan_progress":        "Retrieve real-time progress metrics for a plan, including completion percentages and estimated time to delivery.",
		"plan_activate":        "Transition a plan to the 'active' state, signaling the orchestrator that tasks are ready for agent assignment.",
		"plan_create_from_prd": "Automatically generate a structured development plan by parsing requirements from a PRD document.",
		"plan_dashboard":       "Retrieve a unified overview of plan health, including progress, active agents, and pending human reviews.",
		"plan_get_active":      "Convenience tool to get the currently active plan for the user's workspace without requiring an ID.",
		"phase_create":         "Define a new logical phase within a development plan to group related tasks and establish milestones.",
		"phase_update":         "Update the status or configuration of a development phase as agents progress through the assigned tasks.",
		"phase_start":          "Explicitly signal the start of a phase, triggering automation hooks and marking its tasks as ready for work.",
		"phase_report":         "Generate a detailed status report for a phase, summarizing completed work and any outstanding issues or risks.",
		"task_create":          "Define a new granular development task within a phase, specifying its title, priority, and implementation details.",
		"task_get":             "Retrieve deep details of a specific task, including its history, assignments, and current persistent state.",
		"task_get_next":        "Retrieve the next unblocked task from the plan hierarchy according to its priority and dependency constraints.",
		"task_update":          "Update task lifecycle state (in_progress, completed, blocked) and provide execution notes or findings.",
		"task_list":            "List tasks within a plan or phase, providing a filtered view of the current work queue based on status.",
		"task_assign_agents":   "Formally assign a task to one or more Skoll agents, creating a link between the plan and the orchestrator.",
		"task_set_blocker":     "Mark a task as blocked and provide a detailed reason, preventing further execution until the issue is resolved.",
		"checkpoint_open":      "Establish a quality checkpoint or human-in-the-loop gate that must be cleared to proceed to the next phase.",
		"checkpoint_approve":   "Submit human approval for a pending quality checkpoint, allowing the development plan to transition.",
		"human_review_pending": "List all items awaiting human inspection or decision across all active development plans.",
		"human_review_decide":  "Submit a final decision (approve/reject) for a human review request, providing mandatory rationale notes.",
		"hati_register_commit": "Link a physical code commit to a Hati task or plan for lifecycle tracking and audit purposes.",
		"task_claim":           "Reserve a task for exclusive execution by an agent, preventing concurrency conflicts in multi-agent environments.",
		"task_release":         "Release a previously claimed task, making it available for other agents or marking it as unassigned.",
		"tyr_snapshot":         "Get a quality snapshot from Tyr with current standards results, SAST findings, and metrics.",

		// Skoll (Orchestration)
		"agent_list":             "Retrieve a comprehensive list of all registered AI agents in Skoll, including their current status (idle/working) and active task assignments.",
		"agent_context":          "Retrieve the full operational context for an agent, including its currently assigned tasks, loaded skills, and recent execution history.",
		"agent_activate":         "Activate an AI agent and mark it as available for task delegation. This allows Skoll to include the agent in automated team formation.",
		"agent_handoff":          "Formally hand off development context and current task state from one agent to another to ensure continuity in specialized workflows.",
		"agent_register_work":    "Register that an agent is initiating work on a specific plan or task. Used for orchestration tracking and resource management.",
		"agent_unregister_work":  "Release an agent from its current work assignment and mark the task execution as finished in the orchestration layer.",
		"agent_list_work":        "List all active work records across the ecosystem, providing visibility into which agents are working on which plans and tasks.",
		"agent_create":           "Register and configure a new autonomous AI agent in Skoll with a specific role (backend, frontend, qa, etc.) and tool access rules.",
		"agent_get":              "Retrieve detailed configuration and real-time status for a specific AI agent by its unique identifier.",
		"agent_specialized_list": "Filter and list registered agents by their specialized role or type, facilitating targeted task delegation by the orchestrator.",
		"agent_assign_task":      "Directly assign a Hati task to a specific Skoll agent for execution. This creates a link between planning and orchestration layers.",
		"agent_complete_task":    "Mark an agent's task assignment as completed in Skoll and provide the final result or output generated during execution.",
		"agent_heartbeat":        "Submit a periodic heartbeat signal from an active agent to indicate it is still processing its assigned task and prevent timeouts.",
		"agent_skills_get":       "Retrieve the complete catalog of skills and automated capabilities currently assigned to and usable by a specific AI agent.",
		"team_create":            "Form a new collaborative agent team and associate it with a specific project path for orchestrated multi-agent development.",
		"team_status":            "Get the real-time status of a project team, including composition, individual agent health, and collective progress on assigned tasks.",
		"team_get":               "Retrieve the full details and member list of a specific agent team using its unique team identifier.",
		"rule_list":              "List all orchestration and quality rules stored in Skoll, optionally filtered by category or severity level.",
		"rule_check":             "Validate if a specific action or proposed code change complies with the active orchestration rules for the current context.",
		"rule_get":               "Retrieve the full content, patterns, and enforcement logic of a specific orchestration rule by its unique identifier.",
		"rule_create_or_reuse":   "Persistence layer for rules: creates a new rule or returns an existing one if a match is found based on name and category.",
		"rule_create_from_prd":   "Autonomous rule generation: analyzes PRD requirements to create specific development constraints and orchestration rules.",
		"skill_list":             "List all available automated skills and capabilities that can be assigned to agents across the Ragnarok ecosystem.",
		"skill_load":             "Load the full executable structure and instructions of a specific skill. Used by agents to acquire new capabilities dynamically.",
		"skill_search":           "Search the global skill repository using keywords or natural language descriptions to find existing capabilities for reuse.",
		"skill_verify":           "Perform a structural and semantic verification of a skill definition to ensure it meets the required Ragnarok architectural standards.",
		"skill_version_check":    "Check if a specific skill has an updated version available in the central repository to ensure agents use the latest logic.",
		"skill_read_file":        "Read the raw source file or configuration content of a specific skill for manual inspection or debugging purposes.",
		"skills_import":          "Batch import multiple skill definitions from a local directory or remote URL into the Skoll orchestration layer.",
		"skills_update":          "Update an existing skill to its latest available version, ensuring all agents using it benefit from improvements and fixes.",
		"skoll_status":           "Retrieve the overall health and operational status of the Skoll orchestration module, including active agent counts.",
		"skoll_validate":         "Perform a comprehensive validation of the orchestration layer, checking for rule conflicts and agent misconfigurations.",
		"tyr_bootstrap":          "Initialize a project by importing essential bootstrap data (rules, skills, base agents) into the Tyr and Fenrir layers.",
		// Skoll — Task Execution
		"task_execute":   "Initiate the physical execution of a Hati task by a Skoll agent. This transitions the task from 'planned' to 'running'.",
		"task_delegate":  "Delegate a complex task to multiple agents simultaneously, creating a parallel execution workflow within the orchestration layer.",
		"task_status":    "Retrieve the real-time execution status of a running task, including heartbeat logs and partial output from assigned agents.",
		"task_heartbeat": "Submit an execution-level heartbeat to Skoll to maintain the active status of a long-running automated task.",
		"task_complete":  "Submit the final results of a task execution to Skoll, including success/failure status and any audit logs generated.",
		"task_cancel":    "Abort a running task execution and release all assigned agent resources. Requires a cancellation reason for the logs.",

		// Tyr — Quality
		"pkg_check":            "Evaluate a software package for security vulnerabilities, typosquatting risks, license compliance, and overall trust score.",
		"pkg_license":          "Perform a deep analysis of a package's license to ensure legal compliance with the project's licensing strategy.",
		"pkg_audit":            "Execute a comprehensive audit of a package, combining security scans, quality checks, and community reputation analysis.",
		"pkg_audit_snapshot":   "Retrieve a historical snapshot of all previously audited packages, including their risk levels and resolution status.",
		"pkg_audit_continuous": "Enable continuous auditing of project dependencies, triggering alerts in Tyr whenever a new vulnerability is discovered.",
		"sast_run":             "Execute a Static Analysis Security Testing (SAST) scan on the project codebase to identify potential vulnerabilities and bugs.",
		"sast_findings":        "Retrieve all findings from the latest SAST scans, optionally filtered by severity level (Critical, High, Medium, Low).",
		"sast_resolve":         "Formally resolve a SAST finding by providing a resolution note, which is then persisted to Fenrir for future reference.",
		"standard_list":        "List all available quality standards and compliance checks registered in the Tyr quality module.",
		"standard_run":         "Execute a specific quality standard check against the codebase and return a detailed pass/fail report with remediation steps.",
		"standard_run_all":     "Execute the complete suite of quality standards and compliance checks, providing a high-level project health summary.",
		"standard_create":      "Create a new custom quality standard or compliance rule for the project, defining its category and validation logic.",
		"standard_update":      "Update an existing quality standard's definition, metadata, or orchestration parameters.",
		"quality_gate":         "Execute a consolidated quality audit (SAST + standards + pre-commit) to ensure a project path meets all governance requirements.",
		"precommit_validate":   "Run pre-commit validation checks, including linting, formatting, and unit tests, to ensure code quality before submission.",
		"precommit_autofix":    "Automatically apply fixes for common pre-commit validation issues, such as code formatting and import organization.",
		"tyr_status":           "Retrieve the high-level operational status and quality metrics from the Tyr module, including total findings and pass rates.",

		// New tools
		"ragnarok_help":          "Get usage instructions and recommended workflows for Ragnarok. Call this first when you start a session.",
		"ragnarok_status":        "Ragnarok MCP Ecosystem Status: all modules health, DB record counts, active plans, and total tool count.",
		"session_context_full":   "Get full session context in one call: active plan + pending tasks + recent memory + active agents.",
		"analyze_stack_with_llm": "Use LLM to analyze project stack and requirements, recommending specialized agents. Returns a prompt to execute and a parser for the LLM response.",
	}
	if desc, ok := descriptions[name]; ok {
		return desc
	}
	return fmt.Sprintf("Ragnarok tool: %s", name)
}

func getToolInputSchema(name string) string {
	schemas := map[string]string{
		// Fenrir (Memory)
		"mem_save":            `{"type":"object","properties":{"title":{"type":"string","description":"Brief descriptive title of the observation"},"type":{"type":"string","enum":["bugfix","decision","pattern","discovery","config","refactor"],"description":"Category of the observation"},"what":{"type":"string","description":"Detailed description of what was done or discovered"},"why":{"type":"string","description":"Rationale behind the action or decision"},"where":{"type":"string","description":"File paths or modules affected"},"learned":{"type":"string","description":"Key takeaway or lesson for future reference"}},"required":["title","type"]}`,
		"mem_find":            `{"type":"object","properties":{"query":{"type":"string","description":"Search terms for FTS5 lookup"},"limit":{"type":"integer","description":"Maximum number of results to return"}},"required":["query"]}`,
		"mem_context":         `{"type":"object","properties":{"module":{"type":"string","description":"Filter context by module name or path"}}}`,
		"mem_timeline":        `{"type":"object","properties":{"limit":{"type":"integer","description":"Number of recent events to retrieve"}}}`,
		"mem_stats":           `{"type":"object","properties":{}}`,
		"mem_session_start":   `{"type":"object","properties":{"goal":{"type":"string","description":"The main objective of this development session"},"module":{"type":"string","description":"Primary module being worked on"}},"required":["goal"]}`,
		"mem_session_end":     `{"type":"object","properties":{"summary":{"type":"string","description":"Concise summary of session achievements"}}}`,
		"mem_get_observation": `{"type":"object","properties":{"id":{"type":"string","description":"Unique identifier of the memory observation"}},"required":["id"]}`,
		"mem_project_summary": `{"type":"object","properties":{"project_path":{"type":"string","description":"Optional: project path to summarize"}}}`,
		"mem_save_prompt":     `{"type":"object","properties":{"prompt":{"type":"string","description":"The raw user prompt"},"response":{"type":"string","description":"The AI response to be stored"}},"required":["prompt"]}`,
		"spec_save":           `{"type":"object","properties":{"name":{"type":"string","description":"Name of the specification"},"description":{"type":"string","description":"High-level summary"},"content":{"type":"string","description":"Full specification content in markdown"}},"required":["name"]}`,
		"spec_list":           `{"type":"object","properties":{"module":{"type":"string","description":"Filter specs by module name"}}}`,
		"spec_delta":          `{"type":"object","properties":{"spec_id":{"type":"string","description":"ID of the spec to compare"},"plan_id":{"type":"string","description":"Plan ID to check against"},"type":{"type":"string","description":"Type of delta analysis"},"description":{"type":"string","description":"Context for comparison"}},"required":["spec_id","plan_id"]}`,
		"spec_impact":         `{"type":"object","properties":{"module":{"type":"string","description":"Module path to analyze impact for"}},"required":["module"]}`,
		"spec_check":          `{"type":"object","properties":{"module":{"type":"string","description":"Module path to verify compliance"}},"required":["module"]}`,
		"project_scan":        `{"type":"object","properties":{"path":{"type":"string","description":"Root directory to scan","default":"."},"layer":{"type":"string","enum":["stack","architecture","modules","patterns","config","all"],"description":"Depth of analysis"}}}`,
		"project_bootstrap":   `{"type":"object","properties":{"project_path":{"type":"string","description":"Root path to initialize","default":"."}}}`,
		"skill_generate":      `{"type":"object","properties":{"project_path":{"type":"string","description":"Target project path","default":"."}}}`,
		"rules_generate":      `{"type":"object","properties":{"project_path":{"type":"string","description":"Target project path","default":"."}}}`,
		"standards_generate":  `{"type":"object","properties":{"project_path":{"type":"string","description":"Target project path","default":"."}}}`,
		"prompt_analyze":      `{"type":"object","properties":{}}`,
		"agents_md_get":       `{"type":"object","properties":{"project_path":{"type":"string"}}}`,

		// Hati (Planning)
		"plan_create":          `{"type":"object","properties":{"title":{"type":"string","description":"Main objective of the development plan"},"description":{"type":"string","description":"Detailed context and scope"}},"required":["title"]}`,
		"plan_list":            `{"type":"object","properties":{"status":{"type":"string","enum":["active","completed","abandoned","all"],"description":"Filter plans by lifecycle status"}}}`,
		"plan_get":             `{"type":"object","properties":{"id":{"type":"string","description":"Unique identifier of the plan"}},"required":["id"]}`,
		"plan_complete":        `{"type":"object","properties":{"id":{"type":"string","description":"Plan ID to mark as completed"}},"required":["id"]}`,
		"plan_abandon":         `{"type":"object","properties":{"id":{"type":"string","description":"Plan ID to abandon"},"reason":{"type":"string","description":"Rationale for abandonment"}},"required":["id"]}`,
		"plan_resume":          `{"type":"object","properties":{"id":{"type":"string","description":"Plan ID to resume"}},"required":["id"]}`,
		"plan_revise":          `{"type":"object","properties":{"id":{"type":"string","description":"Plan ID to modify"},"changes":{"type":"string","description":"Description of requested changes in natural language"}},"required":["id","changes"]}`,
		"plan_blockers":        `{"type":"object","properties":{"id":{"type":"string","description":"Plan ID to check for blockers"}},"required":["id"]}`,
		"plan_dependencies":    `{"type":"object","properties":{"plan_id":{"type":"string","description":"Root plan ID"},"action":{"type":"string","enum":["list","add"],"description":"Operation to perform"},"depends_on_plan_id":{"type":"string","description":"Target plan ID for dependency link"}},"required":["plan_id"]}`,
		"plan_progress":        `{"type":"object","properties":{"plan_id":{"type":"string","description":"Plan ID to retrieve metrics for"}},"required":["plan_id"]}`,
		"plan_activate":        `{"type":"object","properties":{"plan_id":{"type":"string","description":"Plan ID to move to active pool"}},"required":["plan_id"]}`,
		"plan_create_from_prd": `{"type":"object","properties":{"prd_id":{"type":"string","description":"Parsed PRD identifier from prd_parse"},"title":{"type":"string","description":"Override default plan title"}},"required":["prd_id"]}`,
		"plan_dashboard":       `{"type":"object","properties":{"plan_id":{"type":"string","description":"Plan ID for full dashboard retrieval"}},"required":["plan_id"]}`,
		"plan_get_active":      `{"type":"object","properties":{}}`,
		"phase_create":         `{"type":"object","properties":{"plan_id":{"type":"string","description":"Parent plan ID"},"title":{"type":"string","description":"Phase name"},"description":{"type":"string","description":"Context and goals"},"order_num":{"type":"integer","description":"Execution sequence number"}},"required":["plan_id","title"]}`,
		"phase_update":         `{"type":"object","properties":{"phase_id":{"type":"string","description":"Phase ID to update"},"status":{"type":"string","enum":["pending","in_progress","completed","blocked"],"description":"New lifecycle status"}},"required":["phase_id"]}`,
		"phase_start":          `{"type":"object","properties":{"plan_id":{"type":"string","description":"Plan ID containing the phase"},"name":{"type":"string","description":"Name of the phase to start"}},"required":["plan_id","name"]}`,
		"phase_report":         `{"type":"object","properties":{"phase_id":{"type":"string","description":"Phase ID to generate report for"},"content":{"type":"string","description":"Optional status notes"}},"required":["phase_id","content"]}`,
		"task_create":          `{"type":"object","properties":{"phase_id":{"type":"string","description":"Parent phase ID"},"title":{"type":"string","description":"Task summary"},"description":{"type":"string","description":"Detailed implementation steps"},"priority":{"type":"integer","description":"Relative importance (1-100)"}},"required":["phase_id","title"]}`,
		"task_get":             `{"type":"object","properties":{"task_id":{"type":"string","description":"Unique identifier of the task"}},"required":["task_id"]}`,
		"task_get_next":        `{"type":"object","properties":{"plan_id":{"type":"string","description":"Plan ID to scan"},"agent_type":{"type":"string","description":"Optional filter by agent role"},"agent_id":{"type":"string","description":"Optional filter by specific agent"}},"required":["plan_id"]}`,
		"task_update":          `{"type":"object","properties":{"task_id":{"type":"string","description":"Task ID to update"},"status":{"type":"string","enum":["pending","in_progress","completed","blocked"],"description":"New status"},"notes":{"type":"string","description":"Execution logs or findings"}},"required":["task_id"]}`,
		"task_list":            `{"type":"object","properties":{"phase_id":{"type":"string","description":"Filter by phase"},"plan_id":{"type":"string","description":"Filter by plan"}}}`,
		"task_assign_agents":   `{"type":"object","properties":{"task_id":{"type":"string","description":"Task ID for assignment"},"agent_ids":{"type":"array","items":{"type":"string"},"description":"List of Skoll agent IDs"}},"required":["task_id","agent_ids"]}`,
		"task_claim":           `{"type":"object","properties":{"task_id":{"type":"string","description":"Task ID to claim"},"agent_id":{"type":"string","description":"Agent ID claiming the task"},"context_id":{"type":"string","description":"Context identifier for the claim"}},"required":["task_id","agent_id"]}`,
		"task_release":         `{"type":"object","properties":{"task_id":{"type":"string","description":"Task ID to release"},"agent_id":{"type":"string","description":"Agent ID releasing the task"}},"required":["task_id","agent_id"]}`,
		"task_set_blocker":     `{"type":"object","properties":{"task_id":{"type":"string","description":"Blocked task ID"},"blocker":{"type":"string","description":"Detailed reason or dependency blocking progress"}},"required":["task_id","blocker"]}`,
		"checkpoint_open":      `{"type":"object","properties":{"plan_id":{"type":"string","description":"Plan ID for checkpoint"},"type":{"type":"string","enum":["PRD_APPROVAL","PHASE_APPROVAL","DEPLOY_APPROVAL"],"description":"Type of validation"},"phase_id":{"type":"string","description":"Optional phase ID"}},"required":["plan_id","type"]}`,
		"checkpoint_approve":   `{"type":"object","properties":{"checkpoint_id":{"type":"string","description":"Checkpoint ID to approve"},"approver":{"type":"string","description":"Name of approver"},"notes":{"type":"string","description":"Approval comments"}},"required":["checkpoint_id"]}`,
		"human_review_pending": `{"type":"object","properties":{}}`,
		"human_review_decide":  `{"type":"object","properties":{"review_id":{"type":"string"},"decision":{"type":"string","enum":["approved","rejected"]},"notes":{"type":"string"}},"required":["review_id","decision"]}`,
		"hati_register_commit": `{"type":"object","properties":{"commit":{"type":"string"}},"required":["commit"]}`,

		// Skoll (Orchestration)
		"agent_create":           `{"type":"object","properties":{"name":{"type":"string","description":"Identifying name for the agent"},"role":{"type":"string","enum":["backend","frontend","qa","devops","architect","pm"],"description":"Specialized functional role"},"skills":{"type":"array","items":{"type":"string"},"description":"List of initial skill names"},"tools":{"type":"array","items":{"type":"string"},"description":"Allowed MCP tool patterns"}},"required":["name","role"]}`,
		"agent_get":              `{"type":"object","properties":{"agent_id":{"type":"string","description":"Unique agent identifier"}},"required":["agent_id"]}`,
		"agent_activate":         `{"type":"object","properties":{"agent_id":{"type":"string","description":"Agent ID to enable for orchestration"}},"required":["agent_id"]}`,
		"agent_handoff":          `{"type":"object","properties":{"target_agent_id":{"type":"string","description":"Agent ID to receive the context"},"context_summary":{"type":"string","description":"Brief overview of the state being transferred"}},"required":["target_agent_id"]}`,
		"agent_assign_task":      `{"type":"object","properties":{"agent_id":{"type":"string","description":"Skoll agent ID"},"task_id":{"type":"string","description":"Hati task ID"}},"required":["agent_id","task_id"]}`,
		"agent_heartbeat":        `{"type":"object","properties":{"agent_id":{"type":"string","description":"Active agent ID"}},"required":["agent_id"]}`,
		"team_create":            `{"type":"object","properties":{"name":{"type":"string","description":"Project team name (e.g., 'Core Dev Team')"},"project_path":{"type":"string","description":"Root directory for team context"}},"required":["name"]}`,
		"team_get":               `{"type":"object","properties":{"team_id":{"type":"string","description":"Unique team identifier"}},"required":["team_id"]}`,
		"rule_check":             `{"type":"object","properties":{"rule_id":{"type":"string","description":"Rule ID to validate"},"context":{"type":"string","description":"Action context or code snippet"}},"required":["rule_id"]}`,
		"rule_get":               `{"type":"object","properties":{"rule_id":{"type":"string","description":"Unique rule identifier"}},"required":["rule_id"]}`,
		"skill_load":             `{"type":"object","properties":{"name":{"type":"string","description":"Skill name to load into agent context"}},"required":["name"]}`,
		"skill_search":           `{"type":"object","properties":{"query":{"type":"string","description":"Search terms for skill discovery"}},"required":["query"]}`,
		"skill_verify":           `{"type":"object","properties":{"name":{"type":"string","description":"Skill name to validate"}},"required":["name"]}`,
		"skill_read_file":        `{"type":"object","properties":{"path":{"type":"string","description":"Local path to skill definition file"}},"required":["path"]}`,
		"skills_import":          `{"type":"object","properties":{"path":{"type":"string","description":"Directory containing skill definitions"}},"required":["path"]}`,
		"skills_update":          `{"type":"object","properties":{"name":{"type":"string","description":"Skill name to update"}},"required":["name"]}`,
		"task_execute":           `{"type":"object","properties":{"task_id":{"type":"string","description":"Hati task ID to run"},"agent_id":{"type":"string","description":"Skoll agent ID assigned to the run"}},"required":["task_id","agent_id"]}`,
		"task_delegate":          `{"type":"object","properties":{"task_id":{"type":"string","description":"Hati task ID to distribute"},"agent_ids":{"type":"array","items":{"type":"string"},"description":"List of agents for parallel execution"}},"required":["task_id","agent_ids"]}`,
		"task_status":            `{"type":"object","properties":{"execution_id":{"type":"string","description":"Execution ID from task_execute or delegate"}},"required":["execution_id"]}`,
		"task_heartbeat":         `{"type":"object","properties":{"execution_id":{"type":"string","description":"Running execution identifier"}},"required":["execution_id"]}`,
		"task_complete":          `{"type":"object","properties":{"execution_id":{"type":"string","description":"Execution ID to finalize"},"result":{"type":"string","description":"Serialized final output or error report"}},"required":["execution_id"]}`,
		"task_cancel":            `{"type":"object","properties":{"execution_id":{"type":"string","description":"Execution ID to abort"},"reason":{"type":"string","description":"Rationale for cancellation"}},"required":["execution_id"]}`,
		"pkg_check":              `{"type":"object","properties":{"name":{"type":"string","description":"Package name and version (e.g., 'express@4.18.2')"},"ecosystem":{"type":"string","enum":["npm","pypi","go","maven"],"description":"Package ecosystem"}},"required":["name"]}`,
		"pkg_license":            `{"type":"object","properties":{"name":{"type":"string","description":"Package name to verify license for"}},"required":["name"]}`,
		"pkg_audit":              `{"type":"object","properties":{"name":{"type":"string","description":"Package name for deep audit"}},"required":["name"]}`,
		"pkg_audit_continuous":   `{"type":"object","properties":{"path":{"type":"string","description":"Project root with manifest files (package.json, go.mod, etc.)"}},"required":["path"]}`,
		"standard_run_all":       `{"type":"object","properties":{}}`,
		"standard_create":        `{"type":"object","properties":{"name":{"type":"string"},"description":{"type":"string"},"category":{"type":"string"}},"required":["name"]}`,
		"standard_update":        `{"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"description":{"type":"string"},"category":{"type":"string"}},"required":["id"]}`,
		"quality_gate":           `{"type":"object","properties":{"path":{"type":"string","description":"Root directory to perform quality checks"},"plan_id":{"type":"string","description":"Optional plan ID to associate results"}},"required":["path"]}`,
		"precommit_validate":     `{"type":"object","properties":{"path":{"type":"string","description":"Root directory to perform validation checks"}},"required":["path"]}`,
		"precommit_autofix":      `{"type":"object","properties":{"path":{"type":"string","description":"Root directory to apply fixes"}},"required":["path"]}`,
		"tyr_bootstrap":          `{"type":"object","properties":{"project_path":{"type":"string","description":"Root project directory to initialize quality module"}},"required":["project_path"]}`,
		"tyr_snapshot":           `{"type":"object","properties":{"project_path":{"type":"string","description":"Project path to retrieve assessment for"}}}`,
		"ragnarok_help":          `{"type":"object","properties":{"topic":{"type":"string","enum":["getting_started","project_init","planning","memory","quality","orchestration","workflows"],"description":"Specific help topic to retrieve"}}}`,
		"ragnarok_status":        `{"type":"object","properties":{"verbose":{"type":"boolean","description":"Include detailed module metrics"}}}`,
		"session_context_full":   `{"type":"object","properties":{"plan_id":{"type":"string","description":"Optional: focus context on a specific plan"}}}`,
		"analyze_stack_with_llm": `{"type":"object","properties":{"project_path":{"type":"string","description":"Project root path"},"prd_file":{"type":"string","description":"Optional PRD file path"},"requirements":{"type":"array","items":{"type":"object"},"description":"Array of requirement objects with title and type"}},"required":["project_path"]}`,
	}
	if schema, ok := schemas[name]; ok {
		return schema
	}
	return `{"type":"object","properties":{}}`
}
